### PR TITLE
Fix/ctr+c

### LINKED ISSUE #63: Ctrl+C Ignored When Running Login Command
**Describe the bug**
Process is not terminated when pressing **Ctrl+C**

**To Reproduce**
1. Run `mg login --scopes user.read`
2. Press Ctrl + C
3. Observe that process is not terminated

**Expected behavior**
The process is expected to terminate after pressing Ctrl+C

**Screenshots**
N/A

**Additional context**
N/A 
[AB#7669](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7669)

### PR DESCRIPTION
**Pull request by jobala**
## Overview
Add support for killing the CLI process with **CTRL+C**

### Demo

N/A

### Notes

N/A

## Testing Instructions

* Pull these changes
* Run `mg login --scopes user.read`
* Press **CTRL + C**
* Observe that the process is terminated

Fixes #63

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
I tried this from pwsh. Ran the command and the  auth prompt in the browser opened. Ctrl+c didn't cancel the process and I had to manually close the pwsh instance. I take it that you aren't seeing this behavior, you used PowerShell 5 or the command prompt. My main dev machine crashed (not related) on me or else I'd try the other scenarios.

**Comment by jobala** [comment]
@MIchaelMainer this fails on Windows because azure-identity blocks and waits for a response once it opens the browser. I have created [#18533](https://github.com/Azure/azure-sdk-for-python/issues/18533) on the azure-identity repo to track the issue.

**Comment by jobala** [comment]
@MIchaelMainer based on the response from the thread in the azure-identity repo, I think we should merge this in and document that users should use CTRL+Break instead of CTRL+C on Windows. Let me know what you think.

**Review by MIchaelMainer — APPROVED** [review]
ctrl + break is fine by me for now. We do need to document it.

**Comment by jobala** [comment]
@MIchaelMainer I have documented this under the wiki's [known issues](https://github.com/microsoftgraph/msgraph-cli/wiki/Known-Issues) section.

**Pull request merged**
