### PR TITLE
Add working Homebrew formula

### LINKED ISSUE #152: MacOS Support
Adding support for installation on MacOS. 
[AB#10021](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10021)

### PR DESCRIPTION
**Pull request by calebkiage**
## Overview

Add a homebrew formula to install the msgraph-cli

## Testing Instructions

* checkout branch
* Run the commands below to install formula

```
$ cd Formula
$ brew install --build-from-source ./msgraph-cli.rb
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-cli/pull/184)

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
Looks like I need to run in the virtualenv. Will update soon.....

```
Error: uninitialized constant Language::Python::Virtualenv
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/MichaelMainer/Repos/msgraph-cli/Formula/msgraph-cli.rb:2:in `<class:MsgraphCli>'
/Users/MichaelMainer/Repos/msgraph-cli/Formula/msgraph-cli.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
```

**Review by MIchaelMainer — APPROVED** [review]
Was able to run on Mac

**Review by jobala — CHANGES_REQUESTED** [review]
Does this mean customers on MacOS have to pull this repo to install msgraph-cli?

[Requesting Changes to avoid this getting merged before we finish this conversation]

**Comment by calebkiage** [comment]
> Does this mean customers on MacOS have to pull this repo to install msgraph-cli?
> 
> [Requesting Changes to avoid this getting merged before we finish this conversation]

No. Once this is merged, users will use `brew tap microsoftgraph/msgraph-cli https://github.com/microsoftgraph/msgraph-cli` and then `brew install msgraph-cli`

**Pull request merged**
